name: Setup Python Virtual Environment
description: Sets up Python, installs uv, and creates the virtual environment with dependencies.

inputs:
  only-dev:
    description: Whether to install only dev dependencies
    default: 'false'
    required: false
  install-lsl:
    description: Whether to install LSL dependencies
    default: 'false'
    required: false
  resolution:
    description: Dependency resolution strategy
    default: 'highest'
    required: false
  python-version:
    description: Python version to use
    required: false
    default: ''
  

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false  # Disable uv's built-in caching

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        
    # Install system dependencies (from your old action file)
    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux' && inputs.install-lsl == 'true'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
          libgl1 libglu-dev mesa-utils cmake build-essential xvfb xauth x11-apps \
          libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS' && inputs.install-lsl == 'true'
      shell: bash
      run: |
        brew install --formula cmake
        brew install --cask xquartz
        brew install --formula libxkbcommon qt@6
        echo "DYLD_FRAMEWORK_PATH=$(brew --prefix qt@6)/lib:$DYLD_FRAMEWORK_PATH" >> $GITHUB_ENV

    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows' && inputs.install-lsl == 'true'
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25.0'
        
    # Install LSL if needed
    - name: Install LSL on Windows
      if: inputs.install-lsl == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        # Install vcpkg if not already installed
        if (-not (Test-Path $env:VCPKG_INSTALLATION_ROOT)) {
          git clone https://github.com/Microsoft/vcpkg.git $env:TEMP\vcpkg
          cd $env:TEMP\vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
          $env:VCPKG_INSTALLATION_ROOT = "$env:TEMP\vcpkg"
          echo "VCPKG_INSTALLATION_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
          echo "$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_PATH
        }

        # Install liblsl
        vcpkg install liblsl
        
        # Add to PATH
        echo "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin" >> $env:GITHUB_PATH

    - name: Install LSL on macOS (Homebrew)
      if: inputs.install-lsl == 'true' && runner.os == 'macOS'
      shell: bash
      run: |
        brew install labstreaminglayer/tap/lsl

    - name: Install LSL on Ubuntu
      if: inputs.install-lsl == 'true' && runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        git clone --depth=1 https://github.com/sccn/liblsl.git
        cd liblsl
        mkdir build && cd build
        cmake ..
        make -j
        sudo make install
        sudo ldconfig

    - name: Install dependencies
      shell: bash
      run: |-
        if [[ "${{ inputs.only-dev }}" == "true" ]]; then
          uv sync --only-dev --resolution=${{ inputs.resolution }}
        else
          uv sync --resolution=${{ inputs.resolution }}
        fi